### ISSUE TITLE
Add Error Handling if Settings Have Not Been Configured

### ISSUE THREAD

**Issue by jacksonhuang21** [legiongis/clitoolbox#13]
ArcGIS v. 10.4.1
CLI Toolbox v1.2 "Extract Data From Enterprise" tool will not execute. Attempted multiple times after several restarts.

Error message:
Traceback (most recent call last):
  File "C:\Users\jacksonhuang\Desktop\MATT clitoolbox-master\scripts\ExtractCLIDataFromEnterprise_v1.0.py", line 14, in <module>
    from clitools.enterprise import ExtractFromEnterpriseSelection
  File "C:\Users\jacksonhuang\Desktop\MATT clitoolbox-master\scripts\clitools\enterprise.py", line 41, in <module>
    from clitools.config import settings
  File "C:\Users\jacksonhuang\Desktop\MATT clitoolbox-master\scripts\clitools\config\__init__.py", line 10, in <module>
    settings = get_settings()
  File "C:\Users\jacksonhuang\Desktop\MATT clitoolbox-master\scripts\clitools\config\__init__.py", line 6, in get_settings
    with open(settings_file,'rb') as f:
IOError: [Errno 2] No such file or directory: 'C:\\Users\\jacksonhuang\\Desktop\\MATT clitoolbox-master\\scripts\\clitools\\config\\settings.json'

Failed to execute (ExtractDataFromEnterprise).
Failed at Tue Oct 31 12:18:01 2017 (Elapsed Time: 0.50 seconds)

**Comment by mradamcox** [comment]
@jacksonhuang21 thanks for logging this. It's not actually an error with that tool, it's an error because with the new version of the toolbox the very first thing you need to do is run the settings configuration tool. This will create the file that is missing and causing this error. I'm going to rename this issue, because the real problem is that there is no graceful error handling to tell the user what the problem is.
